/*
** list_functions.c for list function in /src/
**
** Made by Frederic ODDOU
** Login oddou_f <frederic.oddou@epitech.eu>
**
** Started on  Sat Apr  1 22:20:21 2017 Frederic ODDOU
** Last update Fri Apr 28 19:26:02 2017 Frederic Oddou
*/

#include <stdlib.h>
#include <string.h>
#include "strace.h"

const t_list_functions	g_list_functions[] = {
  {0, "read", &print_number, 3, {&print_number,
				 &print_pointer,
				 &print_number}},
  {1, "write", &print_number, 3, {&print_number,
				  &print_char_pointer,
				  &print_number}},
  {2, "open", &print_number, 2, {&print_char_pointer,
				 &print_flags_open}},
  {3, "close", &print_number, 1, {&print_number}},
  {4, "stat", &print_number, 2, {&print_char_pointer,
				 &print_struct_stat}},
  {5, "fstat", &print_number, 2, {&print_number,
				  &print_struct_stat}},
  {6, "lstat", &print_number, 2, {&print_char_pointer,
				  &print_struct_stat}},
  {7, "poll", &print_number, 3, {&print_pointer,
				 &print_number,
				 &print_number}},
  {8, "lseek", &print_number, 3, {&print_number,
				  &print_number,
				  &print_flags_lseek}},
  {9, "mmap", &print_pointer, 6, {&print_pointer,
				  &print_number,
				  &print_flags_mmap_prot,
				  &print_flags_mmap,
				  &print_number,
				  &print_number}},
  {10, "mprotect", &print_number, 3, {&print_pointer,
				      &print_number,
				      &print_flags_mprotect}},
  {11, "munmap", &print_number, 2, {&print_pointer,
				    &print_number}},
  {12, "brk", &print_pointer, 1, {&print_pointer}},
  {14, "rt_sigprocmask", &print_number, 4, {&print_number,
					    &print_pointer,
					    &print_pointer,
					    &print_number}},
  {16, "ioctl", &print_number, 2, {&print_number,
				   &print_number}},
  {19, "readv", &print_number, 3, {&print_number,
				   &print_pointer,
				   &print_number}},
  {20, "writev", &print_number, 3, {&print_number,
				    &print_pointer,
				    &print_number}},
  {21, "access", &print_number, 2, {&print_char_pointer,
				    &print_flags_access}},
  {22, "pipe", &print_number, 1, {&print_pointer}},
  {23, "select", &print_number, 5, {&print_number,
				    &print_pointer,
				    &print_pointer,
				    &print_pointer,
				    &print_pointer}},
  {24, "sched_yield", &print_number, 0, {}},
  {25, "mremap", &print_pointer, 4, {&print_pointer,
				     &print_number,
				     &print_number,
				     &print_number}},
  {26, "msync", &print_number, 3, {&print_pointer,
				   &print_number,
				   &print_number}},
  {27, "mincore", &print_number, 3, {&print_pointer,
				     &print_number,
				     &print_pointer}},
  {28, "madvise", &print_number, 3, {&print_pointer,
				     &print_number,
				     &print_number}},
  {29, "shmget", &print_number, 3, {&print_number,
				    &print_number,
				    &print_number}},
  {30, "shmat", &print_pointer, 3, {&print_number,
				    &print_pointer,
				    &print_number}},
  {31, "shmctl", &print_number, 3, {&print_number,
				    &print_number,
				    &print_pointer}},
  {32, "dup", &print_number, 1, {&print_number}},
  {33, "dup2", &print_number, 2, {&print_number,
				  &print_number}},
  {34, "pause", &print_number, 0, {}},
  {35, "nanosleep", &print_number, 2, {&print_pointer,
				       &print_pointer}},
  {36, "getitimer", &print_number, 2, {&print_number,
				       &print_pointer}},
  {37, "alarm", &print_number, 1, {&print_number}},
  {38, "setitimer", &print_number, 3, {&print_number,
				       &print_pointer,
				       &print_pointer}},
  {39, "getpid", &print_number, 1, {NULL}},
  {40, "sendfile", &print_number, 4, {&print_number,
				      &print_number,
				      &print_pointer,
				      &print_number}},
  {41, "socket", &print_number, 3, {&print_flags_socket_domain,
				    &print_flags_socket_type,
				    &print_number}},
  {42, "connect", &print_number, 3, {&print_number,
				     &print_pointer,
				     &print_number}},
  {43, "accept", &print_number, 3, {&print_number,
				    &print_pointer,
				    &print_pointer}},
  {44, "sendto", &print_number, 6, {&print_number,
				    &print_pointer,
				    &print_number,
				    &print_number,
				    &print_pointer,
				    &print_number}},
  {45, "recvfrom", &print_number, 6, {&print_number,
				      &print_pointer,
				      &print_number,
				      &print_number,
				      &print_pointer,
                                      &print_pointer}},
  {46, "sendmsg", &print_number, 3, {&print_number,
				     &print_pointer,
				     &print_number}},
  {47, "recvmsg", &print_number, 3, {&print_number,
				     &print_pointer,
				     &print_number}},
  {48, "shutdown", &print_number, 2, {&print_number,
				      &print_number}},
  {49, "bind", &print_number, 3, {&print_number,
				  &print_pointer,
				  &print_number}},
  {50, "listen", &print_number, 2, {&print_number,
				    &print_number}},
  {51, "getsockname", &print_number, 3, {&print_number,
					 &print_pointer,
					 &print_pointer}},
  {52, "getpeername", &print_number, 3, {&print_number,
					 &print_pointer,
					 &print_pointer}},
  {53, "socketpair", &print_number, 4, {&print_number,
					&print_number,
					&print_number,
					&print_pointer}},
  {54, "setsockopt", &print_number, 5, {&print_number,
					&print_number,
					&print_number,
					&print_pointer,
					&print_number}},
  {55, "getsockopt", &print_number, 5, {&print_number,
					&print_number,
					&print_number,
					&print_pointer,
					&print_pointer}},
  {56, "clone", &print_number, 4, {&print_pointer,
				   &print_pointer,
				   &print_number,
				   &print_pointer}},
  {57, "fork", &print_number, 0, {}},
  {58, "vfork", &print_number, 0, {}},
  {59, "execve", &print_number, 3, {&print_char_pointer,
				    &print_pointer,
				    &print_pointer}},
  {60, "exit", NULL, 1, {&print_number}},
  {61, "wait4", &print_number, 4, {&print_number,
				   &print_pointer,
				   &print_number,
				   &print_pointer}},
  {62, "kill", &print_number, 2, {&print_number,
				  &print_number}},
  {63, "uname", &print_number, 1, {&print_pointer}},
  {64, "semget", &print_number, 3, {&print_number,
				    &print_number,
				    &print_number}},
  {65, "semop", &print_number, 3, {&print_number,
				   &print_pointer,
				   &print_number}},
  {66, "semctl", &print_number, 3, {&print_number,
				    &print_number,
				    &print_number}},
  {67, "shmdt", &print_number, 1, {&print_pointer}},
  {68, "msgget", &print_number, 2, {&print_number,
				    &print_number}},
  {69, "msgsnd", &print_number, 4, {&print_number,
				    &print_pointer,
				    &print_number,
				    &print_number}},
  {70, "msgrcv", &print_number, 5, {&print_number,
				    &print_pointer,
				    &print_number,
				    &print_number,
				    &print_number}},
  {71, "msgctl", &print_number, 3, {&print_number,
				    &print_number,
				    &print_pointer}},
  {72, "fcntl", &print_number, 2, {&print_number,
				   &print_number}},
  {73, "flock", &print_number, 2, {&print_number,
				   &print_number}},
  {74, "fsync", &print_number, 1, {&print_number}},
  {75, "fdatasync", &print_number, 1, {&print_number}},
  {76, "truncate", &print_number, 2, {&print_char_pointer,
				      &print_number}},
  {77, "ftruncate", &print_number, 2, {&print_number,
				       &print_number}},
  {78, "getdents", &print_number, 3, {&print_number,
				      &print_pointer,
				      &print_number}},
  {79, "getcwd", &print_char_pointer, 2, {&print_char_pointer,
					  &print_number}},
  {80, "chdir", &print_number, 1, {&print_char_pointer}},
  {81, "fchdir", &print_number, 1, {&print_number}},
  {82, "rename", &print_number, 2, {&print_char_pointer,
				    &print_char_pointer}},
  {83, "mkdir", &print_number, 2, {&print_char_pointer,
				   &print_base8}},
  {84, "rmdir", &print_number, 1, {&print_char_pointer}},
  {85, "creat", &print_number, 2, {&print_char_pointer,
				   &print_number}},
  {86, "link", &print_number, 2, {&print_char_pointer,
				  &print_char_pointer}},
  {87, "unlink", &print_number, 1, {&print_char_pointer}},
  {88, "symlink", &print_number, 2, {&print_char_pointer,
				     &print_char_pointer}},
  {89, "readlink", &print_number, 3, {&print_char_pointer,
				      &print_char_pointer,
				      &print_number}},
  {90, "chmod", &print_number, 2, {&print_char_pointer,
				   &print_number}},
  {91, "fchmod", &print_number, 2, {&print_number,
				    &print_number}},
  {92, "chown", &print_number, 3, {&print_char_pointer,
				   &print_number,
				   &print_number}},
  {93, "fchown", &print_number, 3, {&print_number,
				    &print_number,
				    &print_number}},
  {94, "lchown", &print_number, 3, {&print_char_pointer,
				    &print_number,
				    &print_number}},
  {95, "umask", &print_number, 1, {&print_number}},
  {96, "gettimeofday", &print_number, 2, {&print_pointer,
					  &print_pointer}},
  {97, "getrlimit", &print_number, 2, {&print_number,
				       &print_pointer}},
  {98, "getrusage", &print_number, 2, {&print_number,
				       &print_pointer}},
  {99, "sysinfo", &print_number, 1, {&print_pointer}},
  {100, "times", &print_number, 1, {&print_pointer}},
  {101, "ptrace", &print_number, 4, {&print_number,
				     &print_number,
				     &print_pointer,
				     &print_pointer}},
  {102, "getuid", &print_number, 0, {}},
  {103, "syslog", &print_number, 3, {&print_number,
				     &print_char_pointer,
				     &print_number}},
  {104, "getgid", &print_number, 0, {}},
  {105, "setuid", &print_number, 1, {&print_number}},
  {106, "setgid", &print_number, 1, {&print_number}},
  {107, "geteuid", &print_number, 0, {}},
  {108, "getegid", &print_number, 0, {}},
  {109, "setpgid", &print_number, 2, {&print_number,
				      &print_number}},
  {110, "getppid", &print_number, 0, {}},
  {111, "getpgrp", &print_number, 0, {}},
  {112, "setsid", &print_number, 0, {}},
  {113, "setreuid", &print_number, 2, {&print_number,
				       &print_number}},
  {114, "setregid", &print_number, 2, {&print_number,
				       &print_number}},
  {115, "getgroups", &print_number, 2, {&print_number,
					&print_pointer}},
  {116, "setgroups", &print_number, 2, {&print_number,
					&print_pointer}},
  {117, "setresuid", &print_number, 3, {&print_number,
					&print_number,
					&print_number}},
  {118, "getresuid", &print_number, 3, {&print_pointer,
					&print_pointer,
					&print_pointer}},
  {119, "setresgid", &print_number, 3, {&print_number,
					&print_number,
					&print_number}},
  {120, "getresgid", &print_number, 3, {&print_pointer,
					&print_pointer,
					&print_pointer}},
  {121, "getpgid", &print_number, 1, {&print_number}},
  {122, "setfsuid", &print_number, 1, {&print_number}},
  {123, "setfsgid", &print_number, 1, {&print_number}},
  {124, "getsid", &print_number, 1, {&print_number}},
  {125, "capget", &print_number, 2, {&print_pointer,
				     &print_pointer}},
  {126, "capset", &print_number, 2, {&print_pointer,
				     &print_pointer}},
  {129, "rt_sigqueueinfo", &print_number, 3, {&print_number,
					      &print_number,
					      &print_pointer}},
  {131, "sigaltstack", &print_number, 2, {&print_pointer,
					  &print_pointer}},
  {132, "utime", &print_number, 2, {&print_char_pointer,
				    &print_pointer}},
  {133, "mknod", &print_number, 3, {&print_char_pointer,
				    &print_number,
				    &print_number}},
  {134, "uselib", &print_number, 1, {&print_char_pointer}},
  {135, "personality", &print_number, 1, {&print_number}},
  {136, "ustat", &print_number, 2, {&print_number,
				    &print_pointer}},
  {137, "statfs", &print_number, 2, {&print_char_pointer,
				     &print_pointer}},
  {138, "fstatfs", &print_number, 2, {&print_number,
				      &print_pointer}},
  {139, "sysfs", &print_number, 2, {&print_number,
				    &print_char_pointer}},
  {140, "getpriority", &print_number, 2, {&print_number,
					  &print_number}},
  {141, "setpriority", &print_number, 3, {&print_number,
					  &print_number,
					  &print_number}},
  {142, "sched_setparam", &print_number, 2, {&print_number,
					     &print_pointer}},
  {143, "sched_getparam", &print_number, 2, {&print_number,
					     &print_pointer}},
  {144, "sched_setscheduler", &print_number, 3, {&print_number,
						 &print_number,
						 &print_pointer}},
  {145, "sched_getscheduler", &print_number, 1, {&print_number}},
  {146, "sched_get_priority_max", &print_number, 1, {&print_number}},
  {147, "sched_get_priority_min", &print_number, 1, {&print_number}},
  {148, "sched_rr_get_interval", &print_number, 2, {&print_number,
						    &print_pointer}},
  {149, "mlock", &print_number, 2, {&print_pointer,
				    &print_number}},
  {150, "munlock", &print_number, 2, {&print_pointer,
				      &print_number}},
  {151, "mlockall", &print_number, 1, {&print_number}},
  {152, "munlockall", &print_number, 0, {}},
  {153, "vhangup", &print_number, 0, {}},
  {154, "modify_ldt", &print_number, 3, {&print_number,
					 &print_pointer,
					 &print_number}},
  {155, "pivot_root", &print_number, 2, {&print_char_pointer,
					 &print_char_pointer}},
  {156, "_sysctl", &print_number, 1, {&print_pointer}},
  {157, "prctl", &print_number, 5, {&print_number,
				    &print_number,
				    &print_number,
				    &print_number,
				    &print_number}},
  {158, "arch_prctl", &print_number, 2, {&print_flags_arch_prctl,
					 &print_pointer}},
  {159, "adjtimex", &print_number, 1, {&print_pointer}},
  {160, "setrlimit", &print_number, 2, {&print_number,
					&print_pointer}},
  {161, "chroot", &print_number, 1, {&print_char_pointer}},
  {163, "acct", &print_number, 1, {&print_char_pointer}},
  {164, "settimeofday", &print_number, 2, {&print_pointer,
					   &print_pointer}},
  {165, "mount", &print_number, 5, {&print_char_pointer,
				    &print_char_pointer,
				    &print_char_pointer,
				    &print_number,
				    &print_pointer}},
  {166, "umount2", &print_number, 2, {&print_char_pointer,
				      &print_number}},
  {167, "swapon", &print_number, 2, {&print_char_pointer,
				     &print_number}},
  {168, "swapoff", &print_number, 1, {&print_char_pointer}},
  {169, "reboot", &print_number, 4, {&print_number,
				     &print_number,
				     &print_number,
				     &print_pointer}},
  {170, "sethostname", &print_number, 2, {&print_char_pointer,
					  &print_number}},
  {171, "setdomainname", &print_number, 2, {&print_char_pointer,
					    &print_number}},
  {172, "iopl", &print_number, 1, {&print_number}},
  {173, "ioperm", &print_number, 3, {&print_number,
				     &print_number,
				     &print_number}},
  {174, "create_module", &print_char_pointer, 2, {&print_char_pointer,
						  &print_number}},
  {175, "init_module", &print_number, 3, {&print_pointer,
					  &print_number,
					  &print_char_pointer}},
  {176, "delete_module", &print_number, 2, {&print_char_pointer,
					    &print_number}},
  {177, "get_kernel_syms", &print_number, 1, {&print_pointer}},
  {178, "query_module", &print_number, 5, {&print_char_pointer,
					   &print_number,
					   &print_pointer,
					   &print_number,
					   &print_pointer}},
  {179, "quotactl", &print_number, 4, {&print_number,
				       &print_char_pointer,
				       &print_number,
				       &print_char_pointer}},
  {180, "nfsservctl", &print_number, 3, {&print_number,
					 &print_pointer,
					 &print_pointer}},
  {186, "gettid", &print_number, 0, {}},
  {187, "readahead", &print_number, 3, {&print_number,
					&print_number,
					&print_number}},
  {188, "setxattr", &print_number, 5, {&print_char_pointer,
				       &print_char_pointer,
				       &print_pointer,
				       &print_number,
				       &print_number}},
  {189, "lsetxattr", &print_number, 5, {&print_char_pointer,
					&print_char_pointer,
					&print_pointer,
					&print_number,
					&print_number}},
  {190, "fsetxattr", &print_number, 5, {&print_number,
					&print_char_pointer,
					&print_pointer,
					&print_number,
                                        &print_number}},
  {191, "getxattr", &print_number, 4, {&print_char_pointer,
				       &print_char_pointer,
				       &print_pointer,
				       &print_number}},
  {192, "lgetxattr", &print_number, 4, {&print_char_pointer,
					&print_char_pointer,
					&print_pointer,
					&print_number}},
  {193, "fgetxattr", &print_number, 4, {&print_number,
					&print_char_pointer,
					&print_pointer,
					&print_number}},
  {194, "listxattr", &print_number, 3, {&print_char_pointer,
					&print_char_pointer,
					&print_number}},
  {195, "llistxattr", &print_number, 3, {&print_char_pointer,
					 &print_char_pointer,
					 &print_number}},
  {196, "flistxattr", &print_number, 3, {&print_number,
					 &print_char_pointer,
					 &print_number}},
  {197, "removexattr", &print_number, 2, {&print_char_pointer,
					  &print_char_pointer}},
  {198, "lremovexattr", &print_number, 2, {&print_char_pointer,
					   &print_char_pointer}},
  {199, "fremovexattr", &print_number, 2, {&print_number,
					   &print_char_pointer}},
  {200, "tkill", &print_number, 2, {&print_number,
				    &print_number}},
  {201, "time", &print_number, 1, {&print_pointer}},
  {202, "futex", &print_number, 6, {&print_pointer,
				    &print_number,
				    &print_number,
				    &print_pointer,
				    &print_pointer,
				    &print_number}},
  {203, "sched_setaffinity", &print_number, 3, {&print_number,
						&print_number,
						&print_pointer}},
  {204, "sched_getaffinity", &print_number, 3, {&print_number,
						&print_number,
						&print_pointer}},
  {205, "set_thread_area", &print_number, 1, {&print_pointer}},
  {206, "io_setup", &print_number, 2, {&print_number,
				       &print_pointer}},
  {207, "io_destroy", &print_number, 1, {&print_pointer}},
  {208, "io_getevents", &print_number, 5, {&print_pointer,
					   &print_number,
					   &print_number,
					   &print_pointer,
					   &print_pointer}},
  {209, "io_submit", &print_number, 3, {&print_pointer,
					&print_number,
					&print_pointer}},
  {210, "io_cancel", &print_number, 3, {&print_pointer,
					&print_pointer,
					&print_pointer}},
  {211, "get_thread_area", &print_number, 1, {&print_pointer}},
  {212, "lookup_dcookie", &print_number, 3, {&print_number,
					     &print_char_pointer,
                                             &print_number}},
  {213, "epoll_create", &print_number, 1, {&print_number}},
  {216, "remap_file_pages", &print_number, 5, {&print_pointer,
					       &print_number,
					       &print_number,
					       &print_number,
					       &print_number}},
  {217, "getdents64", &print_number, 3, {&print_number,
					 &print_pointer,
					 &print_number}},
  {218, "set_tid_address", &print_number, 1, {&print_pointer}},
  {219, "restart_syscall", &print_number, 0, {}},
  {220, "semtimedop", &print_number, 4, {&print_number,
					 &print_pointer,
					 &print_number,
					 &print_pointer}},
  {222, "timer_create", &print_number, 3, {&print_number,
					   &print_pointer,
					   &print_pointer}},
  {223, "timer_settime", &print_number, 4, {&print_number,
					    &print_number,
					    &print_pointer,
					    &print_pointer}},
  {224, "timer_gettime", &print_number, 2, {&print_number,
					    &print_pointer}},
  {225, "timer_getoverrun", &print_number, 1, {&print_number}},
  {226, "timer_delete", &print_number, 1, {&print_number}},
  {227, "clock_settime", &print_number, 2, {&print_number,
					    &print_pointer}},
  {228, "clock_gettime", &print_number, 2, {&print_number,
					    &print_pointer}},
  {229, "clock_getres", &print_number, 2, {&print_number,
					   &print_pointer}},
  {230, "clock_nanosleep", &print_number, 4, {&print_number,
					      &print_number,
					      &print_pointer,
					      &print_pointer}},
  {231, "exit_group", NULL, 1, {&print_number}},
  {232, "epoll_wait", &print_number, 4, {&print_number,
					 &print_pointer,
					 &print_number,
					 &print_number}},
  {233, "epoll_ctl", &print_number, 4, {&print_number,
					&print_number,
					&print_number,
					&print_pointer}},
  {234, "tgkill", &print_number, 3, {&print_number,
				     &print_number,
				     &print_number}},
  {235, "utimes", &print_number, 2, {&print_char_pointer,
				     &print_pointer}},
  {237, "mbind", &print_number, 6, {&print_pointer,
				    &print_number,
				    &print_number,
				    &print_pointer,
				    &print_number,
				    &print_number}},
  {238, "set_mempolicy", &print_number, 3, {&print_number,
					    &print_pointer,
					    &print_number}},
  {239, "get_mempolicy", &print_number, 5, {&print_pointer,
					    &print_pointer,
					    &print_number,
					    &print_pointer,
					    &print_number}},
  {240, "mq_open", &print_number, 2, {&print_char_pointer,
				      &print_number}},
  {241, "mq_unlink", &print_number, 1, {&print_char_pointer}},
  {242, "mq_timedsend", &print_number, 5, {&print_number,
					   &print_char_pointer,
					   &print_number,
					   &print_number,
					   &print_pointer}},
  {243, "mq_timedreceive", &print_number, 5, {&print_number,
					      &print_char_pointer,
					      &print_number,
					      &print_pointer,
					      &print_pointer}},
  {244, "mq_notify", &print_number, 2, {&print_number,
					&print_pointer}},
  {245, "mq_getsetattr", &print_number, 3, {&print_number,
					    &print_pointer,
					    &print_pointer}},
  {246, "kexec_load", &print_number, 4, {&print_number,
					 &print_number,
					 &print_pointer,
					 &print_number}},
  {247, "waitid", &print_number, 4, {&print_number,
				     &print_number,
				     &print_pointer,
				     &print_number}},
  {248, "add_key", &print_number, 5, {&print_char_pointer,
				      &print_char_pointer,
				      &print_pointer,
				      &print_number,
				      &print_number}},
  {249, "request_key", &print_number, 4, {&print_char_pointer,
					  &print_char_pointer,
					  &print_char_pointer,
					  &print_number}},
  {251, "ioprio_set", &print_number, 3, {&print_number,
					 &print_number,
					 &print_number}},
  {252, "ioprio_get", &print_number, 2, {&print_number,
					 &print_number}},
  {253, "inotify_init", &print_number, 0, {}},
  {254, "inotify_add_watch", &print_number, 3, {&print_number,
						&print_char_pointer,
						&print_number}},
  {255, "inotify_rm_watch", &print_number, 2, {&print_number,
					       &print_number}},
  {256, "migrate_pages", &print_number, 4, {&print_number,
					    &print_number,
					    &print_pointer,
					    &print_pointer}},
  {257, "openat", &print_number, 3, {&print_number,
				     &print_char_pointer,
				     &print_number}},
  {258, "mkdirat", &print_number, 3, {&print_number,
				      &print_char_pointer,
				      &print_number}},
  {259, "mknodat", &print_number, 4, {&print_number,
				      &print_char_pointer,
				      &print_number,
				      &print_number}},
  {260, "fchownat", &print_number, 5, {&print_number,
				       &print_char_pointer,
				       &print_number,
				       &print_number,
                                       &print_number}},
  {261, "futimesat", &print_number, 3, {&print_number,
					&print_char_pointer,
					&print_pointer}},
  {263, "unlinkat", &print_number, 3, {&print_number,
				       &print_char_pointer,
				       &print_number}},
  {264, "renameat", &print_number, 4, {&print_number,
				       &print_char_pointer,
				       &print_number,
				       &print_char_pointer}},
  {265, "linkat", &print_number, 5, {&print_number,
				     &print_char_pointer,
				     &print_number,
				     &print_char_pointer,
				     &print_number}},
  {266, "symlinkat", &print_number, 3, {&print_char_pointer,
					&print_number,
					&print_char_pointer}},
  {267, "readlinkat", &print_number, 4, {&print_number,
					 &print_char_pointer,
					 &print_char_pointer,
					 &print_number}},
  {268, "fchmodat", &print_number, 4, {&print_number,
				       &print_char_pointer,
				       &print_number,
				       &print_number}},
  {269, "faccessat", &print_number, 4, {&print_number,
					&print_char_pointer,
					&print_number,
					&print_number}},
  {271, "ppoll", &print_number, 4, {&print_pointer,
				    &print_number,
				    &print_pointer,
				    &print_pointer}},
  {272, "unshare", &print_number, 1, {&print_number}},
  {273, "set_robust_list", &print_number, 2, {&print_pointer,
					      &print_number}},
  {274, "get_robust_list", &print_number, 3, {&print_number,
					      &print_pointer,
					      &print_pointer}},
  {275, "splice", &print_number, 6, {&print_number,
				     &print_pointer,
				     &print_number,
				     &print_pointer,
				     &print_number,
				     &print_number}},
  {276, "tee", &print_number, 4, {&print_number,
				  &print_number,
				  &print_number,
				  &print_number}},
  {277, "sync_file_range", &print_number, 4, {&print_number,
					      &print_number,
					      &print_number,
					      &print_number}},
  {278, "vmsplice", &print_number, 4, {&print_number,
				       &print_pointer,
				       &print_number,
				       &print_number}},
  {279, "move_pages", &print_number, 6, {&print_number,
					 &print_number,
					 &print_pointer,
					 &print_pointer,
                                         &print_pointer,
					 &print_number}},
  {280, "utimensat", &print_number, 4, {&print_number,
					&print_char_pointer,
					&print_pointer,
					&print_number}},
  {281, "epoll_pwait", &print_number, 5, {&print_number,
					  &print_pointer,
					  &print_number,
					  &print_number,
					  &print_pointer}},
  {282, "signalfd", &print_number, 3, {&print_number,
				       &print_pointer,
				       &print_number}},
  {283, "timerfd_create", &print_number, 2, {&print_number,
					     &print_number}},
  {284, "eventfd", &print_number, 2, {&print_number,
				      &print_number}},
  {285, "fallocate", &print_number, 4, {&print_number,
					&print_number,
					&print_number,
					&print_number}},
  {286, "timerfd_settime", &print_number, 4, {&print_number,
					      &print_number,
					      &print_pointer,
					      &print_pointer}},
  {287, "timerfd_gettime", &print_number, 2, {&print_number,
					      &print_pointer}},
  {288, "accept4", &print_number, 4, {&print_number,
				      &print_pointer,
				      &print_pointer,
				      &print_number}},
  {291, "epoll_create1", &print_number, 1, {&print_number}},
  {292, "dup3", &print_number, 3, {&print_number,
				   &print_number,
				   &print_number}},
  {293, "pipe2", &print_number, 2, {&print_pointer,
				    &print_number}},
  {294, "inotify_init1", &print_number, 1, {&print_number}},
  {295, "preadv", &print_number, 4, {&print_number,
				     &print_pointer,
				     &print_number,
				     &print_number}},
  {296, "pwritev", &print_number, 4, {&print_number,
				      &print_pointer,
				      &print_number,
				      &print_number}},
  {297, "rt_tgsigqueueinfo", &print_number, 4, {&print_number,
						&print_number,
						&print_number,
						&print_pointer}},
  {298, "perf_event_open", &print_number, 5, {&print_pointer,
					      &print_number,
					      &print_number,
					      &print_number,
					      &print_number}},
  {299, "recvmmsg", &print_number, 5, {&print_number,
				       &print_pointer,
				       &print_number,
				       &print_number,
				       &print_pointer}},
  {300, "fanotify_init", &print_number, 2, {&print_number,
					    &print_number}},
  {301, "fanotify_mark", &print_number, 5, {&print_number,
					    &print_number,
					    &print_number,
					    &print_number,
					    &print_char_pointer}},
  {303, "name_to_handle_at", &print_number, 5, {&print_number,
						&print_char_pointer,
						&print_pointer,
						&print_pointer,
						&print_number}},
  {304, "open_by_handle_at", &print_number, 3, {&print_number,
						&print_pointer,
						&print_number}},
  {306, "syncfs", &print_number, 1, {&print_number}},
  {307, "sendmmsg", &print_number, 4, {&print_number,
				       &print_pointer,
				       &print_number,
				       &print_number}},
  {308, "setns", &print_number, 2, {&print_number,
				    &print_number}},
  {309, "getcpu", &print_number, 3, {&print_pointer,
				     &print_pointer,
				     &print_pointer}},
  {310, "process_vm_readv", &print_number, 6, {&print_number,
					       &print_pointer,
					       &print_number,
					       &print_pointer,
					       &print_number,
					       &print_number}},
  {311, "process_vm_writev", &print_number, 6, {&print_number,
						&print_pointer,
						&print_number,
						&print_pointer,
						&print_number,
						&print_number}},
  {312, "kcmp", &print_number, 5, {&print_number,
				   &print_number,
				   &print_number,
				   &print_number,
				   &print_number}},
  {313, "finit_module", &print_number, 3, {&print_number,
					   &print_char_pointer,
					   &print_number}},
  {314, "sched_setattr", &print_number, 3, {&print_number,
					    &print_pointer,
					    &print_number}},
  {315, "sched_getattr", &print_number, 4, {&print_number,
					    &print_pointer,
					    &print_number,
					    &print_number}},
  {316, "renameat2", &print_number, 5, {&print_number,
					&print_char_pointer,
					&print_number,
					&print_char_pointer,
					&print_number}},
  {317, "seccomp", &print_number, 3, {&print_number,
				      &print_number,
				      &print_pointer}},
  {318, "getrandom", &print_number, 3, {&print_pointer,
					&print_number,
					&print_number}},
  {319, "memfd_create", &print_number, 2, {&print_char_pointer,
					   &print_number}},
  {320, "kexec_file_load", &print_number, 5, {&print_number,
					      &print_number,
					      &print_number,
					      &print_char_pointer,
					      &print_number}},
  {321, "bpf", &print_number, 3, {&print_number,
				  &print_pointer,
				  &print_number}},
  {322, "execveat", &print_number, 5, {&print_number,
				       &print_char_pointer,
				       &print_pointer,
				       &print_pointer,
                                       &print_number}},
  {324, "membarrier", &print_number, 2, {&print_number,
					 &print_number}},
  {325, "mlock2", &print_number, 3, {&print_pointer,
				     &print_number,
				     &print_number}},
  {326, "copy_file_range", &print_number, 6, {&print_number,
					      &print_pointer,
					      &print_number,
					      &print_pointer,
					      &print_number,
					      &print_number}},
  {327, "preadv2", &print_number, 5, {&print_number,
				      &print_pointer,
				      &print_number,
				      &print_number,
				      &print_number}},
  {328, "pwritev2", &print_number, 5, {&print_number,
				       &print_pointer,
				       &print_number,
				       &print_number,
				       &print_number}},
  {329, "pkey_mprotect", &print_number, 4, {&print_pointer,
					    &print_number,
					    &print_number,
					    &print_number}},
  {330, "pkey_alloc", &print_number, 2, {&print_number,
					 &print_number}},
  {331, "pkey_free", &print_number, 1, {&print_number}},
  {0, NULL, 0, 0, {0}},
};

/*
** Finding the syscall array id on the list if it correspond to the rax value.
*/

int			get_rax_strace(unsigned long long rax)
{
  int			i;

  i = 0;
  while (g_list_functions[i].name != NULL)
    {
      if (rax == g_list_functions[i].id)
	return (i);
      i++;
    }
  return (TYPE_END);
}

/*
** If the function name exist on the syscall array, we return true.
*/

bool			get_name_strace(const char *func)
{
  int			i;

  i = 0;
  while (g_list_functions[i].name != NULL)
    {
      if (!strcmp(func, g_list_functions[i].name))
	return (true);
      i++;
    }
  return (false);
}
